---
title: "mapglview"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{mapglview}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, setup, echo= FALSE}

options(tigris_use_cache = TRUE)
knitr::opts_chunk$set(fig.height = 5)

knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

This package exports `mapglview`, a quick function to link to the  [**mapgl**](https://github.com/walkerke/mapgl) package!

Pull some data:

```{r quickdemo}

# devtools::install_github("kmcd39/mapglview")
library(dplyr)
library(sf)
library(mapglview)

# get cities/places in Rhode island
plcs <- tigris::places(state = 44
                       ) |> 
  rename_with(tolower)

```

## First map

Create a quick map with place boundaries, colored by name:

```{r plcs}

plcs |> 
  select(1:5) |> 
  st_boundary() |> 
  mapglview(zcol = "name")
  
```

## Adding data

Add data by passing an existing map as the first argument and data to add as the second:

```{r ripts}

# also get point data footprints from open street maps/geofabrik
ri.osm <- osmextract::oe_get(
  place = "us/rhode-island"
  ,layer = "points"
  ,provider = "geofabrik"
)

ri.pts <- ri.osm  |> 
  filter(!is.na(man_made))

# add the selected point data to mape with place boundaries
plcs |> 
  st_boundary() |> 
  mapglview(palette = "#FFAACC"
            ,size = 2) |> 
  mapglview(ri.pts
            ,zcol = "man_made")
```

## Continuous variables or no variable

The function adapts for continuous variables or no variable

```{r continuous}
# or, map with a continuous variable
plcs |> 
  mapglview(zcol = "aland")


# or, no variable
plcs |> 
  st_boundary() |> 
  mapglview()

```
